export const ReferredPeopleData = [
  {
    id: 1,
    SF_ATS: "1-3ee4",
    candidateName: "Subrahmanyam",
    num: 9191919191,
    email: "sharish@gmail.com",
    Practice: "Continuous Testing - CT",
    Job_Category: "Senior Software Engineer",
    Skills: "Selenium",
    referredBy: "Krish",
    status: "In Progress",
  },
  {
    id: 2,
    SF_ATS: "4-5ee4",
    candidateName: "Sai",
    num: 9988776655,
    email: "sai@gmail.com",
    Practice: "Core Development - CD",
    Job_Category: "Senior Software Engineer",
    Skills: "Core Java + ReactJS",
    referredBy: "Chinna",
    status: "In Progress",
  },
  {
    id: 3,
    SF_ATS: "56-887",
    candidateName: "Saim",
    num: 9191919191,
    email: "sam@gmail.com",
    Practice: "Core Development - CD",
    Job_Category: "Senior Software Engineer",
    Skills: "Core Java + ReactJS",
    referredBy: "Sai",
    status: "Declined",
  },
];
