export const ReferredData = [
  {
    id: 1,
    name: "Subrahmanyam",
    num: 9191919191,
    email: "sharish@gmail.com",
    Practice: "Continuous Testing - CT",
    Job_Category: "Senior Software Engineer",
    Skills: "Selenium",
    hr: "Praveena",
    status: "In Progress",
  },
  {
    id: 2,
    name: "Sai Krishna",
    num: 8181818181,
    email: "skish@gmail.com",
    Practice: "Core Development - CD",
    Job_Category: "Senior Software Engineer",
    Skills: "Core Java + ReactJS",
    hr: "Praveena",
    status: "On Hold",
  },
  {
    id: 3,
    name: "Raghu",
    num: 9323231222,
    email: "raghu@gmail.com",
    Practice: "Core Development - CD",
    Job_Category: "Architect",
    Skills: "Java Architect",
    hr: "Praveena",
    status: "Selected",
  },
  {
    id: 4,
    name: "Saim",
    num: 8181818181,
    email: "sam@gmail.com",
    Practice: "Core Development - CD",
    Job_Category: "Senior Software Engineer",
    Skills: "Core Java + ReactJS",
    hr: "Praveena",
    status: "Declined",
  },
];
